"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RelationalClassStorageDriver = exports.RelationalClassSpecificationRegistry = exports.RelationalClassSpecificationBuilder = exports.RelationalClassSpecification = exports.RelationalProperty = exports.RelationalClassDataHandler = exports.PlainObject = void 0;
var BaseTypes_1 = require("./BaseTypes");
Object.defineProperty(exports, "PlainObject", { enumerable: true, get: function () { return BaseTypes_1.PlainObject; } });
var RelationalClassDataHandler_1 = require("./RelationalClassDataHandler");
Object.defineProperty(exports, "RelationalClassDataHandler", { enumerable: true, get: function () { return RelationalClassDataHandler_1.RelationalClassDataHandler; } });
var RelationalClassSpecification_1 = require("./RelationalClassSpecification");
Object.defineProperty(exports, "RelationalProperty", { enumerable: true, get: function () { return RelationalClassSpecification_1.RelationalProperty; } });
Object.defineProperty(exports, "RelationalClassSpecification", { enumerable: true, get: function () { return RelationalClassSpecification_1.RelationalClassSpecification; } });
var RelationalClassSpecificationBuilder_1 = require("./RelationalClassSpecificationBuilder");
Object.defineProperty(exports, "RelationalClassSpecificationBuilder", { enumerable: true, get: function () { return RelationalClassSpecificationBuilder_1.RelationalClassSpecificationBuilder; } });
var RelationalClassSpecificationRegistry_1 = require("./RelationalClassSpecificationRegistry");
Object.defineProperty(exports, "RelationalClassSpecificationRegistry", { enumerable: true, get: function () { return RelationalClassSpecificationRegistry_1.RelationalClassSpecificationRegistry; } });
var RelationalClassStorageDriver_1 = require("./RelationalClassStorageDriver");
Object.defineProperty(exports, "RelationalClassStorageDriver", { enumerable: true, get: function () { return RelationalClassStorageDriver_1.RelationalClassStorageDriver; } });
